name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: echo "ENVIRONMENT=production" >> $GITHUB_ENV
      - name: Check ENV
        run: echo $ENVIRONMENT
      - name: executing remote ssh commands using ssh key
        run: sh ./deploy.sh --$ENVIRONMENT